# Generated by Django 3.2 on 2021-06-29 13:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import yimei.models


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='名称')),
                ('address', models.CharField(blank=True, help_text='- 至多150字符', max_length=150, null=True, verbose_name='地址')),
                ('tele', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('logo', models.ImageField(blank=True, help_text='仅接受以下格式图片: *.png, *.jpg, *.jpeg', null=True, upload_to=yimei.models.oper_logo_path, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png'])], verbose_name='图标')),
                ('oper_type', models.TextField(choices=[('PRSTDO', '私人工作室'), ('PRHOSP', '私立医院'), ('PUHOSP', '公立医院'), ('INDOCT', '独立医生')], max_length=6, verbose_name='类型')),
                ('oper_license', models.ImageField(blank=True, help_text='仅接受以下格式图片: *.png, *.jpg, *.jpeg', null=True, upload_to=yimei.models.oper_license_path, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png'])], verbose_name='营业执照')),
                ('oper_certificate', models.ImageField(blank=True, help_text='仅接受以下格式图片: *.png, *.jpg, *.jpeg', null=True, upload_to=yimei.models.oper_certificate_path, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png'])], verbose_name='医疗许可证')),
                ('star', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='星级')),
                ('effect', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='效果')),
                ('service', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='服务')),
                ('proficiency', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='专业')),
                ('verified', models.BooleanField(default=False, verbose_name='认证')),
            ],
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
        migrations.AddField(
            model_name='appointment',
            name='accompany',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='陪同人员'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consumption',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='消费预计'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_amount',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='顾客数量'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pre_project',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='铺垫项目'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='precautions',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='注意事项'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='project',
            field=models.CharField(max_length=20, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='vip_lv',
            field=models.PositiveSmallIntegerField(choices=[(0, '普通用户'), (1, 'VIP I'), (2, 'VIP II')], default=0, verbose_name='VIP等级'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yimei.operator', verbose_name='医院名称'),
        ),
        migrations.DeleteModel(
            name='Hospitals',
        ),
    ]
