# Generated by Django 3.2 on 2021-06-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0002_auto_20210629_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='verified',
        ),
        migrations.AddField(
            model_name='operator',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='operator',
            name='province',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='operator',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='邮编'),
        ),
    ]
