# Generated by Django 3.2 on 2021-06-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0003_auto_20210630_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='认证'),
        ),
    ]
