# Generated by Django 3.2 on 2021-06-30 03:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0005_operator_rebate'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='rebate_lv0',
            field=models.IntegerField(default=0, help_text='请输入正整数，如返佣比例30%，则输入30即可', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='普通用户返佣额度'),
        ),
        migrations.AddField(
            model_name='operator',
            name='rebate_lv1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='一级用户返佣额度'),
        ),
        migrations.AddField(
            model_name='operator',
            name='rebate_lv2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='二级用户返佣额度'),
        ),
        migrations.DeleteModel(
            name='Operator_Rebate',
        ),
    ]
