# Generated by Django 3.2 on 2021-07-01 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0009_operator_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='inv_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='邀请码'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='总收入'),
        ),
    ]
