# Generated by Django 3.2 on 2021-07-02 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0011_remove_appointment_create_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='inv_code',
            new_name='invi_code',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='inv_user',
            new_name='invi_user',
        ),
    ]
