# Generated by Django 3.2 on 2021-07-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0015_alter_user_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.UUIDField(primary_key=True, serialize=False, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='交易额')),
                ('transaction_type', models.IntegerField(choices=[(1, '收入'), (2, '提现')], verbose_name='类型')),
                ('note', models.TextField(verbose_name='备注')),
            ],
        ),
        migrations.AddField(
            model_name='user_profile',
            name='realname',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='last_name',
            field=models.CharField(blank=True, default=' ', max_length=150, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
