# Generated by Django 3.2 on 2021-07-08 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0017_transactions_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='realname',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='real_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='tele',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='tell_errmsg_invalid', message='手机号码格式不正确', regex='1(3|4|5|6|7|8|9)\\d{9}')], verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='tele',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='tell_errmsg_invalid', message='手机号码格式不正确', regex='1(3|4|5|6|7|8|9)\\d{9}')], verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='username',
            field=models.CharField(error_messages={'max_length': '用户名长度不得超过150个字符'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='用户名格式错误（·至少5个字符 ·仅包含英文大小写与数字）', regex='^[A-Za-z0-9]+$'), django.core.validators.MinLengthValidator(limit_value=5, message='用户名长度不得少于5个字符')], verbose_name='用户名'),
        ),
    ]
