# Generated by Django 3.2 on 2021-07-10 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0020_auto_20210708_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='tele',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='TellInvalid', message='手机号码格式不正确', regex='1(3|4|5|6|7|8|9)\\d{9}')], verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='tele',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='TellInvalid', message='手机号码格式不正确', regex='1(3|4|5|6|7|8|9)\\d{9}')], verbose_name='手机'),
        ),
    ]
