# Generated by Django 3.2 on 2021-07-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0021_auto_20210710_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False, verbose_name='订单号'),
        ),
    ]
