# Generated by Django 3.2 on 2021-07-10 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0023_alter_transactions_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='total',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='transactions',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yimei.appointment', verbose_name='相关预约'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='holder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yimei.user_profile', verbose_name='账户持有者'),
            preserve_default=False,
        ),
    ]
