# Generated by Django 3.2 on 2021-07-10 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0024_auto_20210710_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='create_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yimei.user_profile', verbose_name='创建者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SUBMIT', '已提交申请'), ('ACCEPT', '已接受申请'), ('PRCESS', '申请处理中'), ('REJECT', '已拒绝申请'), ('SUCESS', '预约成功！'), ('FAILED', '预约失败！'), ('FINISH', '预约完成！')], default='SUBMIT', max_length=10, verbose_name='预约状态'),
        ),
    ]
