# Generated by Django 3.2 on 2021-07-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0025_auto_20210710_0514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_id',
            new_name='id',
        ),
    ]
