# Generated by Django 3.2 on 2021-07-10 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0026_rename_transaction_id_transactions_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yimei.appointment', verbose_name='相关预约'),
        ),
    ]
