# Generated by Django 3.2 on 2021-07-12 08:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0027_alter_transactions_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='最后更改时间')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000000)], verbose_name='提现金额')),
                ('status', models.IntegerField(choices=[(1, '已提交申请'), (2, '审核处理中'), (3, '已放款，请查收'), (4, '交易完成'), (100, '审核失败')], default=1, verbose_name='交易状态')),
                ('applicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
        ),
    ]
