# Generated by Django 3.2 on 2021-07-13 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0028_auto_20210712_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100, message='提现金额低于下限100元'), django.core.validators.MaxValueValidator(10000000, message='提现金额高于上限10000000元')], verbose_name='提现金额'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
