# Generated by Django 3.2 on 2021-07-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yimei', '0030_auto_20210713_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='receive_account',
            field=models.CharField(default='', max_length=200, verbose_name='账号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='method',
            field=models.IntegerField(choices=[(1, '银行转账'), (2, '支付宝'), (3, '微信')], default=1, verbose_name='支付方法'),
            preserve_default=False,
        ),
    ]
